name: 'Deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout-repository:
    runs-on: [coral]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: 'Actuary-LLC/grafana'
          ref: 'main'       
  deploy-task:
    needs: checkout-repository
    runs-on: [coral]
    env:
      TAG: ${{ github.sha }}
    steps:
      - run: | 
          chmod 644 ./loki/config.yaml ./promtail/config.yaml
          docker stack deploy -c grafana.yaml grafana
