name: 'Deploy'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [coral]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: 'Actuary-LLC/grafana'
          ref: 'main'

      - name: Copy configs to persistent storage
        run: |
          cp ./loki/config.yaml /mnt/user/docker/volumes/grafana/loki/config.yaml
          cp ./promtail/config.yaml /mnt/user/docker/volumes/grafana/promtail/config.yaml
          chmod 644 /mnt/user/docker/volumes/grafana/loki/config.yaml
          chmod 644 /mnt/user/docker/volumes/grafana/promtail/config.yaml
      - name: Deploy stack
        run: docker stack deploy -c grafana.yaml grafana
